[package]
name = "v6p"
version = "0.1.0"
edition = "2021"
authors = ["gngppz@gmail.com"]
description = "Random IPv6 request proxy (Fallback Ipv4)"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/gngpp/v6p"
repository = "https://github.com/gngpp/v6p"


[dependencies]
cidr = "0.2"
getopts = "0.2"
hyper = { version = "1.0.1", features = ["http1", "server"] }
hyper-util = { version = "0.1.1", features = ["full"] }
http-body-util = "0.1"
tokio = { version = "1.34.0", features = ["net", "rt-multi-thread", "macros", "io-util"] }
rand = "0.8"
bytes = "1.5.0"
pin-project-lite = "0.2.13"
http = "1.0.0"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1