name: vproxy
version: "0.3.2"
summary: An easy and powerful Rust HTTP/Socks5 Proxy
description: |
  An easy and powerful Rust HTTP/Socks5 proxy that allows initiating network requests using IP binding calculated from CIDR addresses.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

base: core18

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  vproxy:
    plugin: rust
    source: .

apps:
  vproxy:
    command: bin/vproxy
